### ISSUE TITLE
UI: Meta box clutter

### ISSUE THREAD

**Issue by justintadlock** [lightspeeddevelopment/tour-operator#38] opened 2017-03-05 21:15 UTC
The CPTs have a ton of fields in the meta boxes for them.  I'd consider cleaning that up and doing something like tabs.

WooCommerce has a tabbed interface.  Here's a screenshot of a tabbed interface from my portfolio plugin.

![ccp-meta-box](https://cloud.githubusercontent.com/assets/1816309/23591463/8e432036-01b6-11e7-9972-46ae480060e5.png)

Not just wanting to market my own code, but here's a small framework/library I built for doing meta boxes with lots of meta fields: https://github.com/justintadlock/butterbean

There are lots of options though.  Just scrolling through what seems like an endless list of options down the page seems tedious.

**Comment by ashleyshaw** [comment] 2017-03-08 08:23
@justintadlock when you brought this out I considered implementing it, I prefer your boxes to anything else I have seen, how would you go about replacing what we are using CMB2?

**Comment by justintadlock** [comment] 2017-03-08 16:33
If you wanted to go the ButterBean route, you'd have to custom build many of the controls.  It only has basic controls built in.  So, you'd be rebuilding a lot of what's already in CMB2, which may not be desirable.  Just depends on how much time you can invest.

The first option I'd look at is seeing how feasible it is to simply use CMB2 while adding in custom HTML and/or styles.  I'm not really familiar with CMB2, so I'm not sure if you can roll your own meta box HTML output or not.  If it's possible to do this with CMB2, it sure beats writing a lot of extra PHP (and potentially JS) code.

CMB2 is more of a complete meta box solution.  It's going to do everything for you.

ButterBean is more of a UI framework.  It'll probably provide far more flexibility for post meta boxes.  However, it requires more custom coding for anything beyond basic form fields.

So, the first question is simple - _Can you improve the UI with the code you have now?_

**Comment by Desertsnowman** [comment] 2017-06-02 08:12
Restructured the metabox to be sectioned off based on the "CMB Title" row.
![image 2017-06-02 at 10 07 13 am](https://cloud.githubusercontent.com/assets/307466/26716942/c0abf574-477b-11e7-9893-da25f59511b2.png)

**Comment by fmdalpiaz** [comment] 2017-06-02 15:04
Hey @Desertsnowman,
I found some issues on your updates:

### Add new Destination page:

- All tabs fields are inside the _General tab_ when the page is loaded. I've noticed that after you click on another tab, all tabs' fields has started to shown on its right spot. So, the problem is on loading stage.

### Add new Tour page:

- Same problem as in _Destination_ page on the load stage;
- When you click on _Price's tab_, there is no fields on it. Actually, they are shown on the _Gallery's tab_.

### Add new Accommodation page:

- Same problem as in _Destination_ page on the load stage;

**Comment by Desertsnowman** [comment] 2017-06-02 15:19
@fmdalpiaz is this only on "Add New *" pages?

**Comment by fmdalpiaz** [comment] 2017-06-02 16:58
@Desertsnowman yes. So far as I know, these are the only pages that use CMB2, aren't they?

I saw that you fixed de load stage issue.
Now, you only have to fix the _Price vs. Gallery_ tabs on **Add new Tour** page.

**Comment by Desertsnowman** [comment] 2017-06-02 17:05
@fmdalpiaz sorry, I tried to test and get everything, but my power went out. I'll be sure to get it checked in the morning.

**Comment by ashleyshaw** [comment] 2017-06-03 10:47
@Desertsnowman how is this fix going?

**Comment by Desertsnowman** [comment] 2017-06-03 17:43
@ashleyshaw I did it yesterday. Should be solved.

**Comment by krugazul** [comment] 2017-06-06 07:20
@Desertsnowman thanks,  its working perfectly now.  I have merged this back into 1.0.7 and we will merge into master when more issues are fixed.

**Closed by krugazul** 2017-06-06 07:20 UTC
Labels: enhancement
