### ISSUE TITLE
Popup on Tours Archive pull in content from first tour if no excerpt is present.

### ISSUE THREAD

**Issue by jacquesvdhorst** [lightspeeddevelopment/tour-operator#64] opened 2019-02-26 10:00 UTC
Content seems to pull in from the first tour that is related to the destination for that popup. If you add an excerpt to the destination then that fixes the issue. So need change how the popup pulls in information if there is no excerpt available for the destination.

**Comment by JosephLightSpeed** [comment] 2019-03-11 09:43
I have tested on updated version and am not getting this issue. Tested a user site in question and the issue is resolved. Closing this off.

**Closed by JosephLightSpeed** 2019-03-11 09:43 UTC
